def menu_principal():
    print("\n=== Sistema de Frota ===")
    print("1. Cadastrar veículo")
    print("2. Listar veículos")
    print("3. Desativar veículo")
    print("4. Reativar veículo")
    print("5. Cadastrar motorista")
    print("6. Listar motoristas")
    print("7. Desativar motorista")
    print("8. Reativar motorista")
    print("9. Cadastrar viagem")
    print("10. Listar viagens")
    print("0. Sair")
    return input("Escolha uma opção: ")
